### ISSUE TITLE
Plug-in disrupts WordPress functionality

### ISSUE THREAD

**Issue by aprmack** [EssentialBlocks/progress-bars#1]
Hello,

I love this plugin and it does exactly what I hoped on my website. Unfortunately, it doesn't agree with something (my theme?) and causes error messages when activated.

When activated my site looks great and functions fine, and my WP dashboard is also functional, but when I try to create or edit a page or post, I get an error message.

When I tried to edit a page, this is the error I got.

TypeError: r is not a function
at https://c0.wp.com/c/5.5/wp-includes/js/dist/components.min.js:7:394527
at Vb (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react-dom.min.js:104:431)
at Xi (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react-dom.min.js:151:136)
at unstable_runWithPriority (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react.min.js:26:340)
at Ma (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react-dom.min.js:52:280)
at Yb (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react-dom.min.js:150:420)
at Ae (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react-dom.min.js:118:178)
at xi (https://c0.wp.com/c/5.5/wp-includes/js/dist/vendor/react-dom.min.js:39:146)

When I tried to create a page, the error said this:

TypeError: u(…) is not a function
at new t (https://c0.wp.com/p/jetpack/8.9/_inc/blocks/editor.js:18:633406)
at Ag (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:63:107)
at Vg (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:89:442)
at ph (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:217:70)
at lh (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:126:409)
at O (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:121:71)
at ze (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:118:14)
at https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:53:49
at unstable_runWithPriority (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react.min.js:26:340)
at Ma (https://c0.wp.com/c/5.5.1/wp-includes/js/dist/vendor/react-dom.min.js:52:280)

It gave me the option to “attempt recovery,” but when I clicked that button nothing happened.

The only solution seems to be to deactivate the Progress Bars plugin. When it's deactivated everything works just fine, including editing or creating pages/posts.

Is there an update you can release to fix this? I'd really love to use your progress bar if I can.

**Comment by aprmack** [comment]
Hellooooo? Anyone here?

**Comment by aprmack** [comment]
Whelp, that's a negative review from me. Too bad, because I really liked the plugin.

**Comment by Rahat89** [comment]
@aprmack  Sorry for late reply. We have restructured  the plugin and hopefully there is no error now. Please check latest version.
